/* eslint-disable no-confusing-arrow */

"use strict";

const fastifySse = require("../index");

const fastifyModule = require("fastify");
const test = require("tap").test;
const request = require("request");

test("reply.sse could send strings", (tap) => {
  tap.plan(7);

  const fastify = fastifyModule();
  fastify.register(fastifySse, (err) => {
    tap.error(err);
  });

  const data = "hello: world";

  fastify.get("/", (request, reply) => {
    reply.sse(data);
    reply.sse();
  });

  fastify.listen(0, (err) => {
    tap.error(err);

    request({
      method: "GET",
      uri: `http://localhost:${fastify.server.address().port}`
    }, (err, response, body) => {
      tap.error(err);
      tap.strictEqual(response.statusCode, 200);
      tap.strictEqual(response.headers["content-type"], "text/event-stream");
      tap.strictEqual(response.headers["content-encoding"], "identity");
      tap.equal(body, `id: 1\r\ndata: ${data}\r\n\r\nevent: end\r\ndata: \r\n\r\n`);
      fastify.close();
    });
  });
});

test("reply.sse could send objects", (tap) => {
  tap.plan(7);

  const fastify = fastifyModule();
  fastify.register(fastifySse, (err) => {
    tap.error(err);
  });

  const data = {hello: "world"};

  fastify.get("/", (request, reply) => {
    reply.sse(data);
    reply.sse();
  });

  fastify.listen(0, (err) => {
    tap.error(err);

    request({
      method: "GET",
      uri: `http://localhost:${fastify.server.address().port}`
    }, (err, response, body) => {
      tap.error(err);
      tap.strictEqual(response.statusCode, 200);
      tap.strictEqual(response.headers["content-type"], "text/event-stream");
      tap.strictEqual(response.headers["content-encoding"], "identity");
      tap.equal(body, `id: 1\r\ndata: ${JSON.stringify(data)}\r\n\r\nevent: end\r\ndata: \r\n\r\n`);
      fastify.close();
    });
  });
});

test("reply.sse could send event name \"hello\"", (tap) => {
  tap.plan(7);

  const fastify = fastifyModule();
  fastify.register(fastifySse, (err) => {
    tap.error(err);
  });

  const data = {hello: "world"};

  fastify.get("/", (request, reply) => {
    reply.sse(data, {event: "hello"});
    reply.sse();
  });

  fastify.listen(0, (err) => {
    tap.error(err);

    request({
      method: "GET",
      uri: `http://localhost:${fastify.server.address().port}`
    }, (err, response, body) => {
      tap.error(err);
      tap.strictEqual(response.statusCode, 200);
      tap.strictEqual(response.headers["content-type"], "text/event-stream");
      tap.strictEqual(response.headers["content-encoding"], "identity");
      tap.equal(body, `id: 1\r\nevent: hello\r\ndata: ${JSON.stringify(data)}\r\n\r\nevent: end\r\ndata: \r\n\r\n`);
      fastify.close();
    });
  });
});

test("reply.sse could send event name generated by function", (tap) => {
  tap.plan(7);

  const fastify = fastifyModule();
  fastify.register(fastifySse, (err) => {
    tap.error(err);
  });

  const data = {hello: "world"};

  fastify.get("/", (request, reply) => {
    reply.sse(data, {event: (event) => event ? event.hello : undefined});
    reply.sse();
  });

  fastify.listen(0, (err) => {
    tap.error(err);

    request({
      method: "GET",
      uri: `http://localhost:${fastify.server.address().port}`
    }, (err, response, body) => {
      tap.error(err);
      tap.strictEqual(response.statusCode, 200);
      tap.strictEqual(response.headers["content-type"], "text/event-stream");
      tap.strictEqual(response.headers["content-encoding"], "identity");
      tap.equal(body, `id: 1\r\nevent: world\r\ndata: ${JSON.stringify(data)}\r\n\r\nevent: end\r\ndata: \r\n\r\n`);
      fastify.close();
    });
  });
});

test("reply.sse could generate id by function", (tap) => {
  tap.plan(7);

  const fastify = fastifyModule();
  fastify.register(fastifySse, (err) => {
    tap.error(err);
  });

  const data = {hello: "world", num: 4};

  fastify.get("/", (request, reply) => {
    reply.sse(data, {idGenerator: (event) => event ? event.num * 5 : undefined});
    reply.sse();
  });

  fastify.listen(0, (err) => {
    tap.error(err);

    request({
      method: "GET",
      uri: `http://localhost:${fastify.server.address().port}`
    }, (err, response, body) => {
      tap.error(err);
      tap.strictEqual(response.statusCode, 200);
      tap.strictEqual(response.headers["content-type"], "text/event-stream");
      tap.strictEqual(response.headers["content-encoding"], "identity");
      tap.equal(body, `id: ${4 * 5}\r\ndata: ${JSON.stringify(data)}\r\n\r\nevent: end\r\ndata: \r\n\r\n`);
      fastify.close();
    });
  });
});

test("reply.sse does not want id", (tap) => {
  tap.plan(7);

  const fastify = fastifyModule();
  fastify.register(fastifySse, (err) => {
    tap.error(err);
  });

  const data = {hello: "world"};

  fastify.get("/", (request, reply) => {
    reply.sse(data, {idGenerator: null});
    reply.sse();
  });

  fastify.listen(0, (err) => {
    tap.error(err);

    request({
      method: "GET",
      uri: `http://localhost:${fastify.server.address().port}`
    }, (err, response, body) => {
      tap.error(err);
      tap.strictEqual(response.statusCode, 200);
      tap.strictEqual(response.headers["content-type"], "text/event-stream");
      tap.strictEqual(response.headers["content-encoding"], "identity");
      tap.equal(body, `data: ${JSON.stringify(data)}\r\n\r\nevent: end\r\ndata: \r\n\r\n`);
      fastify.close();
    });
  });
});

test("reply.sse throw an error if idGenerator is not valid", (tap) => {
  tap.plan(5);

  const fastify = fastifyModule();
  fastify.register(fastifySse, (err) => {
    tap.error(err);
  });

  const data = {hello: "world"};

  fastify.get("/", (request, reply) => {
    try {
      reply.sse(data, {idGenerator: true});
    } catch (err) {
      tap.ok(err instanceof Error);
      tap.equal(err.message, "Option idGenerator must be a function or null");
    }
    reply.send();
  });

  fastify.listen(0, (err) => {
    tap.error(err);

    request({
      method: "GET",
      uri: `http://localhost:${fastify.server.address().port}`
    }, (err) => {
      tap.error(err);
      fastify.close();
    });
  });
});
